title: DRAGONSWORN
description: Adventure Game
theme: just-the-docs

url: https://dragonswornrpg.com

aux_links:
  Tienda: https://laesquinadelrol.itch.io/
  
logo: /logo.png

favicon_ico: /favicon.png
