title: DRAGONSWORN
description: Adventure Game
theme: just-the-docs

url: https://dragonswornrpg.com

aux_links:
  Tienda: https://laesquinadelrol.itch.io/
  
logo: /logo.png

favicon_ico: /favicon.png

footer_content: "Copyright &copy; 2020-2023 La esquina del rol. Full text of the SRD (not artwork) is licensed by an <a href=\"https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0 International</a>"
